// app.js
export const APP_TITLE_HEADER = 'APP_TITLE_HEADER'
export const APP_SETTINGS = 'APP_SETTINGS'

// auth.js
export const LOGOUT = 'LOGOUT'
export const OAUTH_CLIENT_ID = 'OAUTH_CLIENT_ID'
export const OAUTH_ACCESS_TOKEN = 'OAUTH_ACCESS_TOKEN'
export const OAUTH_ACCESS_TOKEN_EXPIRES_IN = 'OAUTH_ACCESS_TOKEN_EXPIRES_IN'
export const OAUTH_SAVE_REDIRECT_URI = 'OAUTH_SAVE_REDIRECT_URI'

// user.js
export const USER_DETAILS_SET = 'USER_DETAILS_SET'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'
export const USER_DETAILS_FETCH_ERROR = 'USER_DETAILS_FETCH_ERROR'

// queue.js
export const QUEUE_SET = 'QUEUE_SET'
export const QUEUE_RESET = 'QUEUE_RESET'
export const QUEUE_SET_LAST_FILTER = 'QUEUE_SET_LAST_FILTER'
